# Generated by Django 3.1 on 2020-11-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesspal', '0002_auto_20201016_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='calories',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
