# Generated by Django 3.1 on 2020-11-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesspal', '0003_auto_20201101_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='food_eat',
        ),
        migrations.AddField(
            model_name='calories',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitnesspal.profile'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitnesspal.profile'),
        ),
    ]
