# Generated by Django 3.1 on 2020-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesspal', '0004_auto_20201115_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date exercise add'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='met',
            field=models.IntegerField(default=0),
        ),
    ]
