# Generated by Django 3.1 on 2020-11-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesspal', '0005_auto_20201119_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
