# Generated by Django 3.1 on 2020-11-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesspal', '0006_profile_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='calories',
            name='carbohydrates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calories',
            name='fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calories',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calories',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
