# Generated by Django 3.1 on 2020-11-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesspal', '0008_calories_date'),
        ('fitnesspal', '0005_auto_20201128_0020'),
    ]

    operations = [
    ]
