# Generated by Django 3.1 on 2020-11-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesspal', '0009_merge_20201129_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
