# Generated by Django 3.1 on 2020-11-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesspal', '0010_profile_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='limit',
            new_name='goal',
        ),
    ]
