# Generated by Django 3.1.3 on 2020-12-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesspal', '0011_auto_20201129_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='calories',
            name='calcium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calories',
            name='cholesterol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calories',
            name='diet_fiber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calories',
            name='iron',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calories',
            name='sat_fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calories',
            name='sodium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calories',
            name='sugar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calories',
            name='tran_fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calories',
            name='unit',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='calories',
            name='vit_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calories',
            name='vit_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.IntegerField(default=2000),
        ),
    ]
