# Generated by Django 3.1 on 2020-12-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesspal', '0012_auto_20201205_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories',
            name='food_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.IntegerField(default=0),
        ),
    ]
